[build]
  publish = "site-shn-nu/public"
  command = "cd site-shn-nu && hugo --gc --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.73.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
